### ISSUE TITLE
rastermeta failing on some project records

### ISSUE THREAD

**Issue by milleri** [geonetwork-delwp/rastermeta#26]
All contacts and datasets process ok but project run fails after 10 records with:

2019-09-16T12:37:05,141 INFO  [main] - Processing Project '2008-9 Future Coasts Victorian Bathymetric Survey' with ID 7660 uuid 26b5d6116207a26bc82a2ddbbcb30c5e50205832
Exception in thread "main" java.lang.NullPointerException
        at au.gov.vic.delwp.FileXMLWriter.logThrowableMsgStack(FileXMLWriter.java:270)
        at au.gov.vic.delwp.FileXMLWriter.jibxit(FileXMLWriter.java:253)
        at au.gov.vic.delwp.FileXMLWriter.main(FileXMLWriter.java:116)
 
Some projects which fail are:
Processing Project '2009-10 Future Coasts Multibeam Bathymetric Survey' with ID 14804 uuid 5ff8fb65081d5bca5666960127dc9e1ce99ae852
 Processing Project '2009-10 Landsat' with ID 15139 uuid 53b9ba0c303d31e66b88dee7d8cc5f16c6063b7d
 Processing Project '2010 Rapideye' with ID 15140 uuid 4291a7b1629b81b9257fb6b89aae06d39e8c1d65
Processing Project '2008-9 Future Coasts Victorian Bathymetric Survey' with ID 7660 uuid 26b5d6116207a26bc82a2ddbbcb30c5e50205832

I think there must be some problem with the catch block because it didn’t give a full stack trace or cause.  
Presumably this is some issue with the rastermeta data for these records.  Last time I did an update was 28 August so presumably something in the commits on the 29th is failing with these specific datasets.

**Comment by sppigot** [comment]
@milleri Two issues: 1st the print out of the stack trace was failing. getRootCause was returning null and this kind of filtering is overkill so just send the exception throught. So the underlying error now returns something more useful. eg:

java -jar target/rastermeta-2.1.jar -P -d ptest -q 'PROJECTID=14804'
2019-09-16T14:14:24,614 INFO  [main] - Requesting rastermeta project records using:
FROM Project WHERE PROJECTID=14804
2019-09-16T14:14:25,042 INFO  [main] - Processing Project '2009-10 Future Coasts Multibeam Bathymetric Survey' with ID 14804 uuid 5ff8fb65081d5bca5666960127dc9e1ce99ae852
2019-09-16T14:14:25,072 ERROR [main] - Problem whilst processing dataset '5ff8fb65081d5bca5666960127dc9e1ce99ae852'Cause: null value for element "{http://standards.iso.org/iso/19115/-3/gco/1.0}CharacterString" from object of type au.gov.vic.delwp.Project - org.jibx.runtime.JiBXExceptionProcessing of '5ff8fb65081d5bca5666960127dc9e1ce99ae852' aborted

This problem was being returned by project records that don't have a Name field in the Project table (which is mapped to alternateTitle in the -3 record). The fact that this value can be unspecified may be something that should be reported to CIP but the mapping shouldn't fail so I have made it optional.

Now runs ok eg.
root@riedlebay:/usr/local/src/rastermetatool# java -jar target/rastermeta-2.1.jar -P -d ptest -q 'PROJECTID=15139'
2019-09-16T14:20:15,144 INFO  [main] - Requesting rastermeta project records using:
FROM Project WHERE PROJECTID=15139
2019-09-16T14:20:15,505 INFO  [main] - Processing Project '2009-10 Landsat' with ID 15139 uuid 53b9ba0c303d31e66b88dee7d8cc5f16c6063b7d
root@riedlebay:/usr/local/src/rastermetatool#

**Comment by sppigot** [comment]
I am running the complete project dump to make sure all is ok now.

**Comment by sppigot** [comment]
All projects mapped to XML successfully.

**Comment by sppigot** [comment]
Fix advised from CIP is to use the Title field if the Name field is blank.
